spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mirea.project.meditation@gmail.com
    password: mzwyyhfrwurhfldk
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: no-reply@example.com
      text: no-reply
